### ISSUE TITLE
Too much resources requested for launch

### ISSUE THREAD

**Issue by PB12203006** [Stevo15025/tsp_gpu#18]
I met this error, don't know why. Anyway I'll use my original one to run, and adjust my parameters to yours.

But I don't quite understand why in acceptance the random number is

    my randf*=(1.0-0.99999999999)

wouldn't it make the acceptance probability become very large? Because the accept condition is 

    if(p>myrandf)

**Comment by Stevo15025** [comment]
Can you print the exact error and code (if it returns one) that you get back?

And yeah that's a bug fixing now

**Comment by Stevo15025** [comment]
Acceptance prob fixed in  f8491dd

**Comment by Stevo15025** [comment]
From:
http://stackoverflow.com/questions/26201172/cuda-too-many-resources-requested-for-launch

>"Too Many Resources Requested for Launch - This error means that the number of registers available on the multiprocessor is being exceeded. Reduce the number of threads per block to solve the problem."

Maybe try reducing the number of threads (which would be weird because it worked before) or the number of blocks
