### ISSUE TITLE
Moving from SA to Hill Climbing

### ISSUE THREAD

**Issue by Stevo15025** [Stevo15025/tsp_gpu#20]
Once temp gets low enough it may be beneficial to directly force the algorithm to perform hill climbing instead of simulated annealing.

Since we make 100K draws each iteration, even if our prob is very very low of taking a worse place, we still can just because of how many samples we take. it may be best at the end to say, "No you are near your optimum so only accept a better solution at this point."

Or maybe we could just lower the overall probability of acceptance

**Comment by PB12203006** [comment]
Make sense, the acceptance should depend on N. 
How about this, import a new flag,

     if sample space<10, flag=1; else flag=0

and change the acceptance to

    p=p-flag;

and acceptance p can be defined to about 1%/N or less at the end?
