### ISSUE TITLE
Unexpected loss increase

### ISSUE THREAD

**Issue by PB12203006** [Stevo15025/tsp_gpu#22]
I think this is the main obstacle to get lower loss, I'm trying to find out what makes the loss goes higher even if I commented out the acceptance

**Comment by Stevo15025** [comment]
Yeah I'm trying to figure that out too. If you comment out everything but 2opt in main the loss only goes down, so it must be in swap or insert

**Comment by Stevo15025** [comment]
Also don't push anything for the next hour. Going to redo the thing I sent you an email about

**Comment by Stevo15025** [comment]
Distance fixed in  a8f4e0a

With the current code mine is not going down very much at all. Actually I think I may have the probabilities set too low. Trying to find a sweet spot that allows for a .05% increase when the temp starts at 10,000 and the current temp is around 100

**Comment by Stevo15025** [comment]
Also, I would worry less about correcting that and more about having some nice tsp pictures to show tmrw. So far mona looks very nice with a loss of about 7 million

Running Van Gogh from [here](http://www.math.uwaterloo.ca/tsp/data/art/index.html) right now.

Gonna try earring or the world tsp map after this finishes

**Comment by PB12203006** [comment]
Very Very Very important! 

I found what's wrong with swap

**Comment by PB12203006** [comment]
Swap has edge codition:

1**23**456
to
1**32**456

the change of segment is
(12)(23)(34) to (13)(32)(24)
but (23)(32) are equivalent! the change is (13)+(24)-(12)-(34)

and
1**2**3**4**56
to
1**4**3**2**56

change:
(12)(23)(34)(45)to(14)(43)(32)(25)
but (23)(34)=(43)(32), the change is (14)+(25)-(12)-(45)

So, only i-j>2 satisfies the change evaluation in our code, near i,j has different edge condition!

**Comment by PB12203006** [comment]
Correct condition:
1**2**34**5**6
to
1**5**34**2**6

change:(15)(53)(42)(26)-(12)(23)(45)(56)

**Comment by PB12203006** [comment]
So change the sample space to floor(3+exp...)

**Comment by Stevo15025** [comment]
Should insert be changed as well?

**Comment by PB12203006** [comment]
I'm deriving the relation, it should be.

Plus, change the city one's range to

    (4, N-4)

by 

            myrandf *= ((float)(N[0] - 8) - 1.0 + 0.9999999999999999);
		myrandf += 1.0;
		int city_one_swap = (int)truncf(myrandf)+4;

in swap

**Comment by PB12203006** [comment]
there's still some increase, but much better, our original version at the end is totally wrong, the delta dose not suit the condition that the space is 1! So there's always obvious increase at the end!

**Comment by Stevo15025** [comment]
That code represents the bound. Should it never touch the first 4 or last 8?
```cuda
        myrandf *= ((float)(N[0] - 8) - 1.0 + 0.9999999999999999);
	myrandf += 1.0;
	int city_one_swap = (int)truncf(myrandf)+4;
```

Are you using the most recent version? I'm getting no decrease

**Comment by Stevo15025** [comment]
I was able to stop the increasing at low levels by bumping up the constant on the acceptance probability to 300. Though I think that is too high

**Comment by PB12203006** [comment]
the third line

    int city_one_swap = (int)truncf(myrandf)+4;

so city_one never touches first 4 and last 4, but city two can! So those coordinates are still included in the swapping range. limit the city_one in case of the edge condition like swapping (3,1)

**Comment by Stevo15025** [comment]
Fixed in  1080852

**Comment by PB12203006** [comment]
insert is a little more complicated because it's not symmetric

    j<=i-3 || j>=i+2

**Comment by Stevo15025** [comment]
In the following code, note that [A] sets the minimum
```cuda
float myrandf = curand_uniform(&states[tid]);
	myrandf *= ((float)(N[0] - 1) - [A] + 0.9999999999999999);
	myrandf += [A];
myrandf += curand_normal(&states[tid]) * sample_space;
```

From [here](http://stackoverflow.com/questions/18501081/generating-random-number-within-cuda-kernel-in-a-varying-range)

**Comment by PB12203006** [comment]
I think line 4 is redundant, normal dist is ok with sample space to get city_two, but shouldn't city_one be uniformly distributed?

**Comment by Stevo15025** [comment]
Line 4 is 
```
mean + N(0,1) * variance
```

yeah it could probably be distributed uniformly. Mby there is some statistical reason for both of them to be normally distributed, but besides that I can't justify it too much

**Comment by PB12203006** [comment]
I mean like this

    float myrandf = curand_uniform(&states[tid]);
    	myrandf *= ((float)(N[0] - 1-[B]) - [A] + 0.9999999999999999);
    	myrandf += [A];
    city_one=myrandf;
    myrandf += curand_normal(&states[tid]) * sample_space;
    //deal with edge condition
    city_two=myrandf;

**Comment by PB12203006** [comment]
and  N[0]-[B] is maximum, [A] is minimum

**Comment by Stevo15025** [comment]
Can you make a branch of master and try it out?

**Comment by PB12203006** [comment]
I think for cities they are equivalent so the start point city_one should be uniform, we can't say that with the process of evolution some typical indices of cities need more or exchange, but sample space shouldn't be uniform that's reasonable. It represents the range.

**Comment by PB12203006** [comment]
But anyway your mean is uniformly chosen so I think basically there won't be much difference.

**Comment by PB12203006** [comment]
To sum up, lock the city_one in 
    [4,N-4], in swap
    [3,N-3], in insert

**Comment by PB12203006** [comment]
and sample space, s

    |s|>=3, in swap
    s<=-3 or s>=2, in insert

to simplify we can just write

    |s|>=3

as well, sacrificing a little exchange..

**Comment by PB12203006** [comment]
so we have excluded the sequential exchange in both swap and insert, and exactly the change of loss in sequential exchange satisfies 2-opt relation ship, so, adjust the sample space of 2-opt and allow 

    city_two=city_one+2

this condition represents swapping city_one+1 and city_one+2!

**Comment by Stevo15025** [comment]
To be clear
Swap: 4
Insertion: 3
2-opt: 2

**Comment by PB12203006** [comment]
Yes, and remember in 2-opt 

    city_two>city_one

and, if simply set insertion 3 we have to restrict city_one in
    [3,N-4]

in case N-3+3=N, that's forbidden.

**Comment by PB12203006** [comment]
But 3-3=0 is ok, we won't move 0

**Comment by PB12203006** [comment]
2-opt is defferent from the previous two, because city_twp is always bigger than city_one, the city_one's range is

    [0,N-3]

Thus city_two's range is

    [city_one+2, N-2]

**Comment by PB12203006** [comment]
Gosh! I know what's wrong! Our current sampling method is, derivate a range of city_two and sample, for example, 

    city_one=10
    sample space = 5
    city_two_min=5
    city_two_max=15

then we sample from 5 to 15, get city_two, so we have probability to get 

    city_two=11!!!!!

And that's forbidden in swap and insert!!!!!!

So we must filter those values around city_one! either separate the sample space to two parts, or filter the value by an if condition!

**Comment by PB12203006** [comment]
And the current sample_space*rand version still has this problem, we must filter the wrong numbers

**Comment by Stevo15025** [comment]
Fixing now

**Comment by PB12203006** [comment]
My basic idea is, in swap, we only remain positive space, because i,j are equivalent, and in insert, we can write two insert, one forward, one backward. That's easier. Separating the space is complicated to implement in one function

**Comment by PB12203006** [comment]
Yeah！This time we have strictly, theoretically solved the increasing issue! My new swap goes monotonically now! just eliminate the negative space!

**Comment by Stevo15025** [comment]
Can you commit that or make it a branch? I'm not entirely understanding the above

**Comment by PB12203006** [comment]
ok! whole file is complicated, I'll commit a single file contains the change, that would be clearer!

**Comment by Stevo15025** [comment]
That's fine, make a branch and I will work it out!

**Comment by PB12203006** [comment]
I've just committed a file named **fixed sampling.c**  in master, and it contains explicit comments

**Comment by PB12203006** [comment]
insertion is a little more complicated, I committed swap first for you to make sense how it works! Basically the change on insertion is similar.
