### ISSUE TITLE
Local Search

### ISSUE THREAD

**Issue by Stevo15025** [Stevo15025/tsp_gpu#23]
Our mona lisa solution is at 7 Million and the best solution is at 5 million'ish. Looking at our picture vs. the best one, they appear incredibly similar. I think the large difference is due to local areas that they have better optimized. Is there a way for us to do tons of local searches at once? That would probably put us near them.

**Comment by PB12203006** [comment]
My new branch is safe... I ran for 10 hours and output is correct, though not much satisfying, still can see the rough pattern. Perhaps I restricted the acceptance too much and made the code stuck at local minimum for a long time...

I have no idea with more local search, actually this is the key difficulty for dsp, which makes this problem hard. Anyway we're already very fast!

**Comment by PB12203006** [comment]
![image](https://cloud.githubusercontent.com/assets/23200814/20980465/a551f428-bc7e-11e6-853a-21b750197e66.png)

**Comment by Stevo15025** [comment]
Which data set is that?

**Comment by PB12203006** [comment]
sra104815
