### ISSUE TITLE
New branch

### ISSUE THREAD

**Issue by PB12203006** [Stevo15025/tsp_gpu#26]
I worked till now to fix the edge problem but I failed, I really don't know why, because my old version is perfect, **no wrong edge condition, strictly no increase, and insertion works well**. I tried to modify yours but there's still some increase. 

Because I have an unfinished hw due Wednesday morning I have no more time fixing the latest version, so I created this new branch to let you see those ultimate no_problem kernel functions and I think modifying them to suit the latest host code is much easier than debugging the current problematic functions.

**Comment by PB12203006** [comment]
And I have some problems with the concat function, but that's trivial, we can polish those parts after submitting the report.

**Comment by Stevo15025** [comment]
When I compile this and run it nothing happens?

**Comment by Stevo15025** [comment]
And why are there multiple global flags?

**Comment by Stevo15025** [comment]
What is your minimum loss when running on something like mona lisa?

**Comment by PB12203006** [comment]
Remember to revise the file name in code, I couldn't run your automatic read function.

That's for debugging, theoretically, use one flag is ok now

**Comment by Stevo15025** [comment]
okay I'll try it out

**Comment by PB12203006** [comment]
I tried venus and got twice the optimum distance, but it's still decreasing.

**Comment by Stevo15025** [comment]
![image](https://cloud.githubusercontent.com/assets/5857231/21149858/ea0a9790-c12a-11e6-8328-27b20c67e559.png)

Here are the best I have gotten with the current version. I will try this branch now

**Comment by PB12203006** [comment]
really sorry that have no time to do more there days, my brief suggestion is, as long as not changing the range of sampling and the update function, you can simply revise the sample probability part to your current version, and then the edge condition will be fixed.

**Comment by PB12203006** [comment]
Yeah I checked you code, 2opt is really great.

**Comment by PB12203006** [comment]
My update functions will be slightly quicker because you added some unnecessary sync and fence. Too much sync will trade off some speed

**Comment by Stevo15025** [comment]
Just finished with a time of 5,972,815 very very cool!

I'll work on merging this with master

**Comment by Stevo15025** [comment]
What is the error you get when you try to run the master branch?

**Comment by PB12203006** [comment]
Concat function, and cudacheckerror, those are trivial and if I comment
those two out I could run, but I worked all night trying to fix the edge
and increase of kernel functions  by imatating my successful
ones and failed, so I think directly transplanting those successful
functions might be more implementable than debugging the current ones.

2016年12月13日星期二，Steve Bronder <notifications@github.com> 写道：

**Comment by Stevo15025** [comment]
This was merged in  81fbfb4 . I'll make a new commit and comment out the `cudaCheckError()`. Is it the ` Too much resources requested for launch ` error? That may be a windows thing. `cudaCheckError()` should only be run during debugging anyway so I'll fix it up.

As for concat, there's nothing too weird inside of it. What error do you get?
https://github.com/Stevo15025/tsp_gpu/blob/master/kernels/utils.h#L300

**Comment by Stevo15025** [comment]
I believe I added fix to `cudaCheckError()` in  2f49a57  that should fix your problem with that
