### ISSUE TITLE
Thread number

### ISSUE THREAD

**Issue by PB12203006** [Stevo15025/tsp_gpu#9]
I don't know how many threads can we use. Note that in the insertion method we have to refresh the route by shifting some elements, now my algo is one thread shifts one element, that implies that the number of threads must exceed the route length, if not, the shift could not be completed. 

So if wo can not use 100K threads, I have to adjust the kernel function, either let each thread do multiple shift, or limit the local search range.

**Comment by Stevo15025** [comment]
@PB12203006 
Is the answer to this what we talked about in the email? That the grid size must be less than than the number of multiprocessors times the thread capability of the processors?

It may be that we are doing blocking poorly in some areas

**Comment by PB12203006** [comment]
I think it is. The experiment I mentioned shows that when grid
size>multiprocessor*capability, only 1024 threads could successfully
parallel, but when <, the paralell threads number can reach grid size, I.e.
8xxx or 9xxx is ok.
Sorry for the layout, I'm out and replied by cellphone.

2016年11月23日星期三，Steve Bronder <notifications@github.com> 写道：
